image: Visual Studio 2017
platform: Any CPU

environment:
  version: $(APPVEYOR_BUILD_VERSION)

configuration:
- Release

before_build:
  - nuget restore

build:
  project: TypeUtility.sln

after_test:
  - ps: (Get-Content TypeUtility.nuspec) | ForEach-Object { $_ -replace "__version__", "$env:version" } | Set-Content TypeUtility.compiled.nuspec
  - nuget pack TypeUtility.compiled.nuspec -Prop Configuration=Release

artifacts:
  - path: TypeUtility\bin\Release\netstandard1.0\TypeUtility.dll
  - path: TypeUtility\bin\Release\net40\TypeUtility.dll
  - path: TypeUtility.%version%.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: csyDlyeSjDmdYAQ/PK0GYNZ4ofK/yC6vd5ZLPnG2TgujmrAW7fUiQxjDVOWD4XAX
